[2021-11-22 06:36:32,485] {processor.py:163} INFO - Started process (PID=47037) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:36:32,486] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-22 06:36:32,487] {logging_mixin.py:109} INFO - [2021-11-22 06:36:32,487] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:36:32,563] {logging_mixin.py:109} INFO - [2021-11-22 06:36:32,556] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 06:36:32,990] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:36:33,062] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.580 seconds
[2021-11-22 06:39:56,469] {processor.py:163} INFO - Started process (PID=48148) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:39:56,471] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-22 06:39:56,472] {logging_mixin.py:109} INFO - [2021-11-22 06:39:56,472] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:39:56,524] {logging_mixin.py:109} INFO - [2021-11-22 06:39:56,520] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 06:39:56,643] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:39:56,657] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.191 seconds
[2021-11-22 06:42:10,189] {processor.py:163} INFO - Started process (PID=49050) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:42:10,189] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-22 06:42:10,191] {logging_mixin.py:109} INFO - [2021-11-22 06:42:10,190] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:42:10,258] {logging_mixin.py:109} INFO - [2021-11-22 06:42:10,253] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 06:42:10,492] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:42:10,523] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.340 seconds
[2021-11-22 06:45:24,748] {processor.py:163} INFO - Started process (PID=50555) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:45:24,749] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-22 06:45:24,750] {logging_mixin.py:109} INFO - [2021-11-22 06:45:24,750] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:45:24,859] {logging_mixin.py:109} INFO - [2021-11-22 06:45:24,851] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 06:45:25,175] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:45:25,203] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.461 seconds
[2021-11-22 06:48:05,054] {processor.py:163} INFO - Started process (PID=51418) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:48:05,055] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-22 06:48:05,060] {logging_mixin.py:109} INFO - [2021-11-22 06:48:05,060] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:48:05,205] {logging_mixin.py:109} INFO - [2021-11-22 06:48:05,197] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 06:48:05,530] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:48:05,558] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.511 seconds
[2021-11-22 06:50:22,439] {processor.py:163} INFO - Started process (PID=52286) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:50:22,440] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-22 06:50:22,442] {logging_mixin.py:109} INFO - [2021-11-22 06:50:22,441] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:50:22,571] {logging_mixin.py:109} INFO - [2021-11-22 06:50:22,561] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 06:50:22,745] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:50:22,774] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.341 seconds
[2021-11-22 06:53:07,978] {processor.py:163} INFO - Started process (PID=53227) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:53:07,980] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-22 06:53:07,982] {logging_mixin.py:109} INFO - [2021-11-22 06:53:07,982] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:53:08,088] {logging_mixin.py:109} INFO - [2021-11-22 06:53:08,080] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 06:53:08,332] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:53:08,387] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.413 seconds
[2021-11-22 06:56:04,440] {processor.py:163} INFO - Started process (PID=54150) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:56:04,443] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-22 06:56:04,449] {logging_mixin.py:109} INFO - [2021-11-22 06:56:04,448] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:56:04,606] {logging_mixin.py:109} INFO - [2021-11-22 06:56:04,599] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 06:56:04,857] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:56:04,883] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.452 seconds
[2021-11-22 06:58:45,029] {processor.py:163} INFO - Started process (PID=55006) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:58:45,030] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-22 06:58:45,034] {logging_mixin.py:109} INFO - [2021-11-22 06:58:45,033] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:58:45,142] {logging_mixin.py:109} INFO - [2021-11-22 06:58:45,134] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 06:58:45,383] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 06:58:45,405] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.383 seconds
[2021-11-22 07:01:24,191] {processor.py:163} INFO - Started process (PID=55918) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 07:01:24,192] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-22 07:01:24,194] {logging_mixin.py:109} INFO - [2021-11-22 07:01:24,194] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 07:01:24,287] {logging_mixin.py:109} INFO - [2021-11-22 07:01:24,278] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 07:01:24,563] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 07:01:24,590] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.403 seconds
[2021-11-22 07:04:00,184] {processor.py:163} INFO - Started process (PID=56794) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 07:04:00,188] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-22 07:04:00,190] {logging_mixin.py:109} INFO - [2021-11-22 07:04:00,190] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 07:04:00,307] {logging_mixin.py:109} INFO - [2021-11-22 07:04:00,296] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 07:04:00,459] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 07:04:00,475] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.298 seconds
[2021-11-22 07:08:11,716] {processor.py:163} INFO - Started process (PID=58417) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 07:08:11,717] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-22 07:08:11,719] {logging_mixin.py:109} INFO - [2021-11-22 07:08:11,719] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 07:08:11,876] {logging_mixin.py:109} INFO - [2021-11-22 07:08:11,870] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 07:08:12,086] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-22 07:08:12,117] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.405 seconds
