[2021-11-22 06:35:14,902] {processor.py:163} INFO - Started process (PID=46577) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:35:14,903] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-11-22 06:35:14,904] {logging_mixin.py:109} INFO - [2021-11-22 06:35:14,904] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:35:15,019] {logging_mixin.py:109} INFO - [2021-11-22 06:35:15,001] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dag.py", line 2977, in factory
    f(**f_kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 06:35:15,160] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:35:15,178] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.280 seconds
[2021-11-22 06:38:25,319] {processor.py:163} INFO - Started process (PID=47600) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:38:25,321] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-11-22 06:38:25,326] {logging_mixin.py:109} INFO - [2021-11-22 06:38:25,326] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:38:25,490] {logging_mixin.py:109} INFO - [2021-11-22 06:38:25,466] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dag.py", line 2977, in factory
    f(**f_kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 06:38:25,801] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:38:25,843] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.530 seconds
[2021-11-22 06:40:56,066] {processor.py:163} INFO - Started process (PID=48551) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:40:56,067] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-11-22 06:40:56,068] {logging_mixin.py:109} INFO - [2021-11-22 06:40:56,068] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:40:56,191] {logging_mixin.py:109} INFO - [2021-11-22 06:40:56,175] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dag.py", line 2977, in factory
    f(**f_kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 06:40:56,417] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:40:56,452] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.396 seconds
[2021-11-22 06:42:45,034] {processor.py:163} INFO - Started process (PID=49382) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:42:45,034] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-11-22 06:42:45,035] {logging_mixin.py:109} INFO - [2021-11-22 06:42:45,035] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:42:45,089] {logging_mixin.py:109} INFO - [2021-11-22 06:42:45,081] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dag.py", line 2977, in factory
    f(**f_kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 06:42:45,197] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:42:45,209] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.178 seconds
[2021-11-22 06:44:03,014] {processor.py:163} INFO - Started process (PID=50011) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:44:03,015] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-11-22 06:44:03,017] {logging_mixin.py:109} INFO - [2021-11-22 06:44:03,016] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:44:03,119] {logging_mixin.py:109} INFO - [2021-11-22 06:44:03,110] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dag.py", line 2977, in factory
    f(**f_kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 06:44:03,275] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:44:03,295] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.338 seconds
[2021-11-22 06:46:24,123] {processor.py:163} INFO - Started process (PID=50897) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:46:24,124] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-11-22 06:46:24,127] {logging_mixin.py:109} INFO - [2021-11-22 06:46:24,127] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:46:24,288] {logging_mixin.py:109} INFO - [2021-11-22 06:46:24,272] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dag.py", line 2977, in factory
    f(**f_kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 06:46:24,639] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:46:24,672] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.556 seconds
[2021-11-22 06:49:06,637] {processor.py:163} INFO - Started process (PID=51771) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:49:06,638] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-11-22 06:49:06,639] {logging_mixin.py:109} INFO - [2021-11-22 06:49:06,639] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:49:06,727] {logging_mixin.py:109} INFO - [2021-11-22 06:49:06,707] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dag.py", line 2977, in factory
    f(**f_kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 06:49:06,928] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:49:06,992] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.358 seconds
[2021-11-22 06:51:28,338] {processor.py:163} INFO - Started process (PID=52705) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:51:28,340] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-11-22 06:51:28,342] {logging_mixin.py:109} INFO - [2021-11-22 06:51:28,341] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:51:28,600] {logging_mixin.py:109} INFO - [2021-11-22 06:51:28,578] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dag.py", line 2977, in factory
    f(**f_kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 06:51:28,876] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:51:28,914] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.582 seconds
[2021-11-22 06:54:16,823] {processor.py:163} INFO - Started process (PID=53580) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:54:16,825] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-11-22 06:54:16,827] {logging_mixin.py:109} INFO - [2021-11-22 06:54:16,826] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:54:16,959] {logging_mixin.py:109} INFO - [2021-11-22 06:54:16,939] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dag.py", line 2977, in factory
    f(**f_kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 06:54:17,374] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:54:17,402] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.583 seconds
[2021-11-22 06:57:06,368] {processor.py:163} INFO - Started process (PID=54488) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:57:06,369] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-11-22 06:57:06,372] {logging_mixin.py:109} INFO - [2021-11-22 06:57:06,371] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:57:06,493] {logging_mixin.py:109} INFO - [2021-11-22 06:57:06,482] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dag.py", line 2977, in factory
    f(**f_kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 06:57:06,748] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:57:06,785] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.424 seconds
[2021-11-22 06:59:43,513] {processor.py:163} INFO - Started process (PID=55338) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:59:43,514] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-11-22 06:59:43,517] {logging_mixin.py:109} INFO - [2021-11-22 06:59:43,517] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:59:43,623] {logging_mixin.py:109} INFO - [2021-11-22 06:59:43,610] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dag.py", line 2977, in factory
    f(**f_kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 06:59:43,854] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 06:59:43,880] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.373 seconds
[2021-11-22 07:02:28,471] {processor.py:163} INFO - Started process (PID=56260) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 07:02:28,472] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-11-22 07:02:28,474] {logging_mixin.py:109} INFO - [2021-11-22 07:02:28,474] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 07:02:28,584] {logging_mixin.py:109} INFO - [2021-11-22 07:02:28,567] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dag.py", line 2977, in factory
    f(**f_kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 07:02:28,871] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 07:02:28,893] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.427 seconds
[2021-11-22 07:04:51,627] {processor.py:163} INFO - Started process (PID=57037) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 07:04:51,629] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-11-22 07:04:51,631] {logging_mixin.py:109} INFO - [2021-11-22 07:04:51,631] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 07:04:51,767] {logging_mixin.py:109} INFO - [2021-11-22 07:04:51,745] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dag.py", line 2977, in factory
    f(**f_kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 07:04:51,983] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 07:04:52,015] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.405 seconds
[2021-11-22 07:06:27,857] {processor.py:163} INFO - Started process (PID=57890) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 07:06:27,857] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-11-22 07:06:27,859] {logging_mixin.py:109} INFO - [2021-11-22 07:06:27,858] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 07:06:27,939] {logging_mixin.py:109} INFO - [2021-11-22 07:06:27,930] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dag.py", line 2977, in factory
    f(**f_kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-22 07:06:28,128] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-22 07:06:28,149] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.295 seconds
