[2021-11-21 12:03:42,010] {processor.py:163} INFO - Started process (PID=73007) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-21 12:03:42,010] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-11-21 12:03:42,011] {logging_mixin.py:109} INFO - [2021-11-21 12:03:42,011] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-21 12:03:42,076] {logging_mixin.py:109} INFO - [2021-11-21 12:03:42,065] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dag.py", line 2977, in factory
    f(**f_kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-21 12:03:42,148] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-21 12:03:42,158] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.149 seconds
[2021-11-21 12:07:21,126] {processor.py:163} INFO - Started process (PID=75141) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-21 12:07:21,128] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-11-21 12:07:21,129] {logging_mixin.py:109} INFO - [2021-11-21 12:07:21,129] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-21 12:07:21,174] {logging_mixin.py:109} INFO - [2021-11-21 12:07:21,164] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dag.py", line 2977, in factory
    f(**f_kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-21 12:07:21,226] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-21 12:07:21,235] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.110 seconds
[2021-11-21 12:10:41,051] {processor.py:163} INFO - Started process (PID=77013) to work on /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-21 12:10:41,051] {processor.py:625} INFO - Processing file /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2021-11-21 12:10:41,052] {logging_mixin.py:109} INFO - [2021-11-21 12:10:41,052] {dagbag.py:500} INFO - Filling up the DagBag from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-21 12:10:41,095] {logging_mixin.py:109} INFO - [2021-11-21 12:10:41,091] {dagbag.py:334} ERROR - Failed to import: /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/dag.py", line 2977, in factory
    f(**f_kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-21 12:10:41,150] {processor.py:639} WARNING - No viable dags retrieved from /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2021-11-21 12:10:41,160] {processor.py:171} INFO - Processing /Users/macca/Documents/airflow/venv/lib/python3.8/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.110 seconds
